### PR TITLE
Update to 1.27.0

### PR DESCRIPTION
**Pull request by planger**
Contributed on behalf of STMicroelectronics.

Signed-off-by: Philip Langer <planger@eclipsesource.com>

### CODE REVIEW

**Comment by planger** [comment]
@jfaltermeier Can you please review this change? It updates the Theia Playwright Template to Theia 1.27 in the yarn lock and regarding the used playwright version. Thanks!

**Review by jfaltermeier — CHANGES_REQUESTED** [review]
I've tested the changes and the update works very well. 
During testing I've noticed that the Readme seems a bit out of date. 
"There is also a VSCode task available called Run all tests in headless mode." -> This is called "Run all tests"
Also I've had trouble running single tests as described with "yarn ui-tests ...". I had to drop the file-exetenstion for this to work.
Could you please update this as well?

**Comment by planger** [comment]
@jfaltermeier Thanks for the feedback! Nice catch regarding the VS Code task name. I've pushed an update to the readme. Can you please take another look? Thanks!

**Review by jfaltermeier — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
